repos:
  - repo: builtin
    hooks:
      # General
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: detect-private-key
      - id: mixed-line-ending
        args: [--fix=auto]
      - id: fix-byte-order-marker
      - id: check-added-large-files
        args: [--maxkb=50000]
      # Checks if configs parse
      - id: check-toml
      - id: check-yaml

  - repo: local
    hooks:
      - id: statix
        name: statix
        language: system
        pass_filenames: false
        entry: statix check -o errfmt
      - id: deadnix
        name: deadnix
        language: system
        pass_filenames: false
        entry: deadnix
      - id: nix_check
        name: nix_check
        language: system
        pass_filenames: false
        entry: nix flake check
      # - id: treefmt
      #   name: treefmt
      #   language: system
      #   pass_filenames: false
      #   entry: nix fmt
      - id: commitizen
        name: commitizen
        language: system
        pass_filenames: false
        entry: cz check --rev-range v0.1.0..HEAD
