services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # dns
      - "53:53/tcp"
      - "53:53/udp"
      # http
      - "8001:80/tcp"
    environment:
      FTLCONF_dns_listeningMode: "ALL"
      TZ: "America/Sao_Paulo"
      FTLCONF_webserver_api_password: "changeme"
    volumes:
      - "./etc-pihole:/etc/pihole"
    cap_add:
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE
    restart: on-failure
